### ISSUE TITLE
1.7.10版本会混乱更多箱子GTNH分支的配方

### ISSUE THREAD

**Issue by huihiuhuai** [MCTeamPotato/Redirector#11]
如何再现：
1.安装异引定址1.2，更多箱子[https://github.com/GTNewHorizons/ironchest/releases/tag/6.0.85](url)
2.再安装NEI 非官方版，鸡块核心非官方版，Unimixins
3.创建存档，检查铁箱子，钻石箱子，泥土箱子等的合成配方，发现配方错乱，比如钻石箱子的合成配方变成了泥土箱子的

我在配置文件禁用Iron Chest优化之后问题得到了解决，不过还是想让作者知道这个问题，希望你们能够修复。

**Comment by Ecdcaeb** [comment]
https://github.com/MCTeamPotato/Redirector/wiki/What-Happened-to-retro
