### ISSUE TITLE
No Config for `isDeBug = true`

### ISSUE THREAD

**Issue by naqaden** [MCTeamPotato/Redirector#7]
Please add a config to turn [debug](https://github.com/MCTeamPotato/Redirector/blob/ab3c0fb1dad72c97b6a902fe2411231aacbedb3e/src/main/java/com/Hileb/teampotato.redirectionor/RedirectionorTransformer.java#L20) off. It's a lot to sift through in the console. Thanks!

**Comment by Kasualix** [comment]
@Ecdcaeb

**Comment by Ecdcaeb** [comment]
@naqaden 1.3 releases before this issue
